## **Ventajas de NumPy**

In [7]:

import numpy as np 
import pandas as pd

#Crear array de datos 
datos = np.array([112,11,20,37,21,66,468,88]) 
print('Los datos son:', datos) 


#Operaciones aritmeticas al array 

suma = datos + 90 
resta = datos -12 
multiplicacion = datos *10 
division = datos/4 


print('Suma (+90) es:', suma) 

print('Resta (-12) es:', resta) 

print('Multiplicacion (*10) es:', multiplicacion) 

print('Division (/4) es:', division) 

 

# Calcular estadísticas 

media = np.mean(datos) 

desviacion_estandar = np.std(datos) 

maximo = np.max(datos) 

minimo = np.min(datos) 


print('Media:', media) 

print('Desviación estándar:', desviacion_estandar) 

print('Valor máximo:', maximo) 

print('Valor mínimo:', minimo) 

Los datos son: [112  11  20  37  21  66 468  88]
Suma (+90) es: [202 101 110 127 111 156 558 178]
Resta (-12) es: [100  -1   8  25   9  54 456  76]
Multiplicacion (*10) es: [1120  110  200  370  210  660 4680  880]
Division (/4) es: [ 28.     2.75   5.     9.25   5.25  16.5  117.    22.  ]
Media: 102.875
Desviación estándar: 142.00918764291274
Valor máximo: 468
Valor mínimo: 11


## **Ventajas de Pandas**


In [52]:
import pandas as pd

# Crear un DataFrame de ejemplo
data = {
    'Producto': ['A', 'B', 'A', 'B', 'C', 'A', 'C', 'B'],
    'Ventas': [100, 150, 200, 250, 300, 350, 400, 450],
    'Descuento': [10, 20, 15, 25, 10, 20, 30, 25]
}

df = pd.DataFrame(data)

#Filtrar datos: Ventas mayores a 200
ventas_mayores_200 = df[df['Ventas'] > 200]

#Sumar las ventas por producto
ventas_por_producto = df.groupby('Producto')['Ventas'].sum()

#Calcular el precio final después de aplicar descuentos
df['Precio_Final'] = df['Ventas'] - df['Descuento']

#Calcular el promedio de ventas
promedio_ventas = df['Ventas'].mean()

print("Ventas mayores a 200:\n", ventas_mayores_200)
print("\nVentas por producto:\n", ventas_por_producto)
print("\nDataFrame con el precio final calculado:\n", df)
print("\nPromedio de ventas:", promedio_ventas)

Ventas mayores a 200:
   Producto  Ventas  Descuento
3        B     250         25
4        C     300         10
5        A     350         20
6        C     400         30
7        B     450         25

Ventas por producto:
 Producto
A    650
B    850
C    700
Name: Ventas, dtype: int64

DataFrame con el precio final calculado:
   Producto  Ventas  Descuento  Precio_Final
0        A     100         10            90
1        B     150         20           130
2        A     200         15           185
3        B     250         25           225
4        C     300         10           290
5        A     350         20           330
6        C     400         30           370
7        B     450         25           425

Promedio de ventas: 275.0


### **Crear una Serie**

In [ ]:
import pandas as pd 


# Crear una Serie inicial con algunos datos 
serie = pd.Series([1, 2, 3], index=['a', 'b', 'c']) 

print("Serie original:") 

print(serie) 

### **Agregar datos a una Serie**


In [9]:
import pandas as pd

nueva_serie = pd.Series([4, 5, 6], index=['d', 'e', 'f'])
serie = pd.concat([serie, nueva_serie])

print("\nSerie con mas datos:")
print(serie)


Serie con mas datos:
a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64


### **Convertir Series en Data Frame**

In [49]:

import pandas as pd

# Crear el la serie a dataframe
datos = {
    'Nombre': ['Ana', 'Juan', 'Pedro', 'Lucía'],
    'Edad': [28, 34, 29, 24],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla'],
    'Ocupación': ['Ingeniera', 'Doctor', 'Abogado', 'Estudiante']
}

#Agregar los datos
datos['Nombre'].extend(['Carlos', 'Marta', 'Luis', 'Sofía'])
datos['Edad'].extend([30, 27, 32, 26])
datos['Ciudad'].extend(['Bilbao', 'Granada', 'Málaga', 'Zaragoza'])
datos['Ocupación'].extend(['Arquitecto', 'Periodista', 'Profesor', 'Médica'])

df = pd.DataFrame(datos)
df

Nombre  Edad     Ciudad   Ocupación
0     Ana    28     Madrid   Ingeniera
1    Juan    34  Barcelona      Doctor
2   Pedro    29   Valencia     Abogado
3   Lucía    24    Sevilla  Estudiante
4  Carlos    30     Bilbao  Arquitecto
5   Marta    27    Granada  Periodista
6    Luis    32     Málaga    Profesor
7   Sofía    26   Zaragoza      Médica

### **Diccionarios convertir a Serie**

In [20]:
import pandas as pd

data = [ 
        {'Nombre':'Ana', 'Edad': 28,'Ciudad':'Madrid'},
        {'Nombre':'Luis', 'Edad': 34, 'Ciudad':'Barcelona'}, 
        {'Nombre':'María','Edad': 22, 'Ciudad': 'Valencia'},
        {'Nombre':'Pedro','Edad': 45, 'Ciudad': 'Sevilla'},
        {'Nombre':'Laura','Edad': 31, 'Ciudad': 'Bilbao'},
        {'Nombre':'Carlos', 'Edad': 29,'Ciudad': 'Granada'},
        {'Nombre':'Isabel', 'Edad': 27, 'Ciudad': 'Murcia'},
        {'Nombre':'José', 'Edad': 40, 'Ciudad': 'Zaragoza'}
]

df = pd.DataFrame(data)

serie_nombres = pd.Series (df['Nombre'])
                              
print(serie_nombres)

0       Ana
1      Luis
2     María
3     Pedro
4     Laura
5    Carlos
6    Isabel
7      José
Name: Nombre, dtype: object


### **Convertir Diccionario a DataFrame**

In [13]:
import pandas as pd

data = {
    'Nombre':['Ana', 'Juan', 'Carlos'],
    'Edad':[28, 34, 29],
    'Ciudad':['Madrid', 'Barcelona', 'Valencia'],
    'Apellido':['Rodriguez' , 'Sanchez' , 'Mendoza'],
    'Carrera':['LTI' , 'LA' , 'CP'],
    'Matricula':['1866338', '1986553', '1966229']
}

df = pd.DataFrame(data)

print(df)

   Nombre  Edad     Ciudad   Apellido Carrera Matricula
0     Ana    28     Madrid  Rodriguez     LTI   1866338
1    Juan    34  Barcelona    Sanchez      LA   1986553
2  Carlos    29   Valencia    Mendoza      CP   1966229


### **Agregar datos al diccionario**

In [55]:
#DataFrame inicial del diccionario

df= pd.DataFrame({
    'Nombre':['Deyanira','Eugenio','Elvira','Santiago'],
    'Edad':[19,20,33,21],
    'Trabajo':['Veterinaria', 'Consulado', 'Ferreteria','Farmacia']
    
    
})

# Agregar nueva columna

df['Licencia de manejo']= ['Estándar','Tipo A', 'Tipo C', 'Sin licencia']

print(df)

     Nombre  Edad      Trabajo Licencia de manejo
0  Deyanira    19  Veterinaria           Estándar
1   Eugenio    20    Consulado             Tipo A
2    Elvira    33   Ferreteria             Tipo C
3  Santiago    21     Farmacia       Sin licencia


### **Listas de listas Data frame**

In [23]:
import pandas as pd

list_of_lst= [
    [11,22,33,44,55,66],
    [22,44,55,66,77,99],
    [33,66,99,110,133,166]
]

print(f'La lista de lista es:{list_of_lst}')

#Covertir las lista de lista a DataFrame

list_df= pd.DataFrame(list_of_lst)
print(list_df)

La lista de lista es:[[11, 22, 33, 44, 55, 66], [22, 44, 55, 66, 77, 99], [33, 66, 99, 110, 133, 166]]
    0   1   2    3    4    5
0  11  22  33   44   55   66
1  22  44  55   66   77   99
2  33  66  99  110  133  166


### **Agregar listas de listas a dataframe**

In [36]:
import pandas as pd

calif_alu= [
    ['Alicia', 'Español', 88],
    ['Aby', 'Matematicas', 90],
    ['Angela', 'Historia', 100],
    ['Jessica', 'Geografia', 77]
]

# Se puede agregar indice personalizado

df_calif = pd.DataFrame(calif_alu, columns=['Nombre','Materia','Calificacion'], index=['Student1','Student2','Student3','Student4'])

print(df_calif)

#Actualizar las calificaciones usando nuevas listas
calif_alunew= [
    ['Eugenio','Historia', 66],
    ['Mario', 'Matematicas', 77],
    ['Junior','Español', 99],
    ['Juan', 'Geografia', 100]
]

df_calif_new= pd.DataFrame(calif_alunew, columns=['Nombre','Materia','Calificacion'], index=['Student5','Student6','Student7','Student8'])

#Concatenar la listas en df
df_calif_= pd.concat([df_calif,df_calif_new], ignore_index=True)
print(df_calif_)


           Nombre      Materia  Calificacion
Student1   Alicia      Español            88
Student2      Aby  Matematicas            90
Student3   Angela     Historia           100
Student4  Jessica    Geografia            77
    Nombre      Materia  Calificacion
0   Alicia      Español            88
1      Aby  Matematicas            90
2   Angela     Historia           100
3  Jessica    Geografia            77
4  Eugenio     Historia            66
5    Mario  Matematicas            77
6   Junior      Español            99
7     Juan    Geografia           100


### **Crear diccionario para almacenar arrays**

In [38]:
import numpy as np

diccionario = {}
diccionario1 = np.array([1, 2, 3])
diccionario2 = np.array([[4, 5, 6], [7, 8, 9]])
diccionario3 = np.array([10, 11, 12])

print(diccionario1)

[1 2 3]


### **Crear dataFrame en NumPy**

In [51]:
import numpy as np
import pandas as pd

array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

df = pd.DataFrame(array, columns=['A', 'B', 'C'])

print(df)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


### **Crear serie apartir de un array en numpy**

In [45]:
import pandas as pd
import numpy as np

#Se convierte el array en numpy
array_nu = np.array([
    ['Tylenol', '40 mg', 'Tomar cada 8 horas'],
    ['Buscapina', '10mg', 'Tomar cada 12 horas'],
    ['Dorixina', '50 mg', 'Tomar en caso de dolor'],
    ['Ibuprofeno', '150 mg', 'Tomar cada 6 horas']
])

#Convertir el array a dataframe
df=pd.DataFrame(array_nu, columns=['Medicina', 'Dosis', 'Prescripción médica'])
print(df)

#Convertir la columna Medicina en serie
serieMed= df['Medicina']

print(serieMed)



     Medicina   Dosis     Prescripción médica
0     Tylenol   40 mg      Tomar cada 8 horas
1   Buscapina    10mg     Tomar cada 12 horas
2    Dorixina   50 mg  Tomar en caso de dolor
3  Ibuprofeno  150 mg      Tomar cada 6 horas
0       Tylenol
1     Buscapina
2      Dorixina
3    Ibuprofeno
Name: Medicina, dtype: object


##  **Arreglos de Numpy**

### **Unidimencionales**

In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Arreglo unidimensional:")
print(arr)

Arreglo unidimensional:
[1 2 3 4 5]


### **Bidimencionales**

In [46]:
import numpy as np  

# Crear un arreglo bidimensional de numpy  

numpy_array_2d = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])  

# Mostrar el arreglo  

print("Arreglo bidimensional:")  

print(numpy_array_2d) 

Arreglo bidimensional:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### **Ceros y Unos**

In [47]:
import pandas as pd 
import numpy as np  

df_zeros = pd.DataFrame(np.zeros((3, 3)), columns=['A', 'B', 'C']) 

print("DataFrame de ceros:") 

print(df_zeros) 


df_ones = pd.DataFrame(np.ones((4, 2)), columns=['X', 'Y']) 

print("\nDataFrame de unos:") 

print(df_ones) 

DataFrame de ceros:
     A    B    C
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0

DataFrame de unos:
     X    Y
0  1.0  1.0
1  1.0  1.0
2  1.0  1.0
3  1.0  1.0
